# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vmpzxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=20, verbose_name='\u865a\u673a\u540d\u79f0')),
                ('creator', models.CharField(max_length=10, verbose_name='\u521b\u5efa\u4eba')),
                ('user', models.CharField(max_length=10, verbose_name='\u7533\u8bf7\u4eba')),
                ('user_gh', models.CharField(max_length=10, verbose_name='\u7533\u8bf7\u4eba\u5de5\u53f7')),
                ('ssdw', models.CharField(max_length=20, verbose_name='\u6240\u5c5e\u5355\u4f4d')),
                ('office_phone', models.CharField(blank=True, max_length=20, verbose_name='\u529e\u516c\u7535\u8bdd')),
                ('cell_phone', models.CharField(blank=True, max_length=20, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('use', models.CharField(blank=True, max_length=20, verbose_name='\u7528\u9014')),
                ('ip', models.CharField(max_length=16, verbose_name='IP\u5730\u5740')),
                ('mac', models.CharField(blank=True, max_length=16, verbose_name='MAC\u5730\u5740')),
                ('os', models.CharField(max_length=20, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('cpu_hs', models.CharField(max_length=16, verbose_name='CPU\u6838\u6570')),
                ('memory', models.CharField(max_length=10, verbose_name='\u5185\u5b58(GB)')),
                ('harddisk', models.CharField(max_length=10, verbose_name='\u786c\u76d8(GB)')),
                ('create_time', models.DateField(blank=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('zyc', models.CharField(blank=True, max_length=20, verbose_name='\u6240\u5728\u8d44\u6e90\u6c60')),
                ('backup', models.CharField(choices=[(b'True', b'\xe6\x98\xaf'), (b'False', b'\xe5\x90\xa6')], max_length=20, verbose_name='\u662f\u5426\u5907\u4efd')),
                ('policy', models.CharField(blank=True, max_length=20, verbose_name='\u5907\u4efd\u7b56\u7565')),
                ('yxq', models.CharField(max_length=20, verbose_name='\u5ef6\u671f\u6709\u6548\u671f')),
                ('beian', models.CharField(blank=True, choices=[(b'not required', b'\xe6\x97\xa0\xe9\x9c\x80\xe5\xa4\x87\xe6\xa1\x88'), (b'YES', b'\xe6\x98\xaf'), (b'NO', b'\xe5\x90\xa6')], max_length=20, verbose_name='\u662f\u5426\u5907\u6848')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['vm_name', '-create_time'],
                'verbose_name': '\u865a\u62df\u673a\u914d\u7f6e\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u865a\u62df\u673a\u914d\u7f6e\u4fe1\u606f\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='vmpzxx',
            unique_together=set([('vm_name', 'user_gh')]),
        ),
    ]
