# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20181217_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmpzxx',
            name='vc',
            field=models.CharField(blank=True, max_length=20, verbose_name='vcenter\u540d\u79f0'),
        ),
    ]
