# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_vmpzxx_vc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmpzxx',
            name='yxq',
            field=models.DateField(max_length=20, verbose_name='\u5230\u671f\u65f6\u95f4'),
        ),
    ]
