# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20181220_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmpzxx',
            name='create_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='vmpzxx',
            name='yxq',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u5230\u671f\u65f6\u95f4'),
        ),
    ]
