# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20181220_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmpzxx',
            name='backup',
            field=models.CharField(blank=True, choices=[(b'True', b'\xe6\x98\xaf'), (b'False', b'\xe5\x90\xa6')], max_length=20, verbose_name='\u662f\u5426\u5907\u4efd'),
        ),
        migrations.AlterField(
            model_name='vmpzxx',
            name='cpu_hs',
            field=models.CharField(blank=True, max_length=16, verbose_name='CPU\u6838\u6570'),
        ),
        migrations.AlterField(
            model_name='vmpzxx',
            name='creator',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u521b\u5efa\u4eba'),
        ),
        migrations.AlterField(
            model_name='vmpzxx',
            name='harddisk',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u786c\u76d8(GB)'),
        ),
        migrations.AlterField(
            model_name='vmpzxx',
            name='ip',
            field=models.CharField(blank=True, max_length=16, verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='vmpzxx',
            name='memory',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u5185\u5b58(GB)'),
        ),
        migrations.AlterField(
            model_name='vmpzxx',
            name='os',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
        ),
        migrations.AlterField(
            model_name='vmpzxx',
            name='ssdw',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u7533\u8bf7\u4eba\u5355\u4f4d'),
        ),
        migrations.AlterField(
            model_name='vmpzxx',
            name='user',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u7533\u8bf7\u4eba'),
        ),
        migrations.AlterField(
            model_name='vmpzxx',
            name='user_gh',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u7533\u8bf7\u4eba\u5de5\u53f7'),
        ),
        migrations.AlterField(
            model_name='vmpzxx',
            name='vm_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u865a\u673a\u540d\u79f0'),
        ),
    ]
