# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20181220_1426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vmpzxx',
            unique_together=set([]),
        ),
    ]
